In [3]:
import numpy as np

a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [8]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
list=np.arange(20)
print(list)
print([i**2 for i in list])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361]


In [19]:
%timeit [i**2 for i in list]

12.9 µs ± 242 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [23]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
x.ndim

1

In [25]:
x.shape

(10,)

In [26]:
len(x)

10

In [35]:
y=np.array([[1,2],[3,4]])
y

array([[1, 2],
       [3, 4]])

In [36]:
y.shape

(2, 2)

In [37]:
y.ndim

2

In [38]:
len(y)

2

In [39]:
y=np.array([[1,2,3,4],[4,5,6,7],[4,8,9,7]])
y

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [4, 8, 9, 7]])

In [40]:
y.ndim

2

In [41]:
len(y)

3

In [59]:
a=np.arange(9)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [60]:
a.dtype

dtype('int32')

In [61]:
a=np.arange(0,20,5)
a

array([ 0,  5, 10, 15])

In [62]:
a.dtype

dtype('int32')

In [63]:
a=np.linspace(1,30,8)
a

array([ 1.        ,  5.14285714,  9.28571429, 13.42857143, 17.57142857,
       21.71428571, 25.85714286, 30.        ])

In [64]:
a.dtype

dtype('float64')

In [46]:
a=np.ones((9,8))
a

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [50]:
a=np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [52]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
a=np.diag([5,6,7,8,9])
a

array([[5, 0, 0, 0, 0],
       [0, 6, 0, 0, 0],
       [0, 0, 7, 0, 0],
       [0, 0, 0, 8, 0],
       [0, 0, 0, 0, 9]])

In [56]:
a=np.random.rand(10)
a

array([0.65222974, 0.07770581, 0.34468822, 0.34656217, 0.31037882,
       0.5911336 , 0.86611531, 0.17716996, 0.23396634, 0.29986941])

In [57]:
a=np.random.randn(5)
a

array([-0.51539229,  1.19458627, -0.70821409,  0.63307002, -1.96668763])

In [65]:
a=np.array([True,False])
a.dtype

dtype('bool')

In [66]:
a=np.array([6+6j,5+5j])
a.dtype

dtype('complex128')

In [67]:
a=np.array(['sapan','mummy','bhaiya'])
a.dtype

dtype('<U6')

In [68]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
a[6]

6

In [70]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
a[1,2]

6

In [74]:
a=np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [76]:
a[3,3]

4

In [79]:
a[2,2]=5
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 4]])

In [80]:
a=np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [81]:
a[5:]=15
a

array([ 0,  1,  2,  3,  4, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15])

In [ ]:
import numpy as np

In [82]:
a=np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

In [83]:
a=np.arange(10)
a**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [86]:
a=np.ones(4)+1


array([2., 2., 2., 2.])

In [87]:
c=np.diag([1,2,3])
c

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [88]:
c*c

array([[1, 0, 0],
       [0, 4, 0],
       [0, 0, 9]])